eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #defaultZone: http://discoveryserver:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
management:
  zipkin:
    tracing:
      sampling:
        probability: 1.0
spring:
  cloud:
    config:
      override-system-properties: false