server:
  port: 8040

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #defaultZone: http://discoveryserver:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
management:
  zipkin:
    tracing:
      sampling:
        probability: 1.0
spring:

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: paymentConfirmation:com.shoponline.ecommerce.kafka.payment.PaymentConfirmation,orderConfirmation:com.shoponline.ecommerce.kafka.order.OrderConfirmation
  mail:
    host: localhost
    port: 1025
    username: admin
    password: pass
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000


  data:
    mongodb:
      username: admin
      password: pass
      host: localhost
      port: 27017
      database: notification
      authentication-database: admin
  cloud:
    config:
      override-system-properties: false