server:
  port: 8070

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #defaultZone: http://discoveryserver:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
management:
  zipkin:
    tracing:
      sampling:
        probability: 1.0




spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: root
    password: rootroot
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.shoponline.ecommerce.kafka.OrderConfirmation
  cloud:
    config:
      override-system-properties: false

application:
  config:
    #punto alla porta dei microservizi ma solo per il test poi dopo cambio il puntamento con api GW
    #customer-url: http://localhost:8090/api/v1/customers
    #product-url: http://localhost:8050/api/v1/products
    #payment-url: http://localhost:8060/api/v1/payments

    customer-url: http://localhost:8222/api/v1/customers
    product-url: http://localhost:8222/api/v1/products
    payment-url: http://localhost:8222/api/v1/payments

