server:
  port: 8070

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: root
    password: rootroot
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    #punto alla porta dei microservizi ma solo per il test poi dopo cambio il puntamento con api GW
    #customer-url: http://localhost:8090/api/v1/customers
    #product-url: http://localhost:8050/api/v1/products
    #payment-url: http://localhost:8060/api/v1/payments

    customer-url: http://localhost:8222/api/v1/customers
    product-url: http://localhost:8222/api/v1/products
    payment-url: http://localhost:8222/api/v1/payments

